server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0到1 之间,1则表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2019?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities   #所有entitiy别名类所在包

eureka:
  client:
    register-with-eureka: true #true表示向注册中心注册自己
    fetch-registry: true #是否从Eurekaserver抓取已有的注册信息,默认true,点单无所无,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka     #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka     #集群版
  instance:
    instance-id: payment8001
    #访问路径可以显示ip
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上限,单位为秒(默认90秒),超时将剔除服务
    #lease-expiration-duration-in-seconds: 2